//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoyaltyDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaigns_mk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public campaigns_mk()
        {
            this.campaign_articul = new HashSet<campaign_articul>();
            this.campaign_groups = new HashSet<campaign_groups>();
            this.campaign_participant = new HashSet<campaign_participant>();
            this.campaign_sub_groups = new HashSet<campaign_sub_groups>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public bool is_run { get; set; }
        public Nullable<long> type_id { get; set; }
        public Nullable<decimal> margin_markets { get; set; }
        public Nullable<decimal> margin_lavel_0 { get; set; }
        public Nullable<decimal> margin_lavel_1 { get; set; }
        public Nullable<decimal> margin_lavel_2 { get; set; }
        public Nullable<decimal> margin_lavel_3 { get; set; }
        public Nullable<long> group_id_0 { get; set; }
        public Nullable<long> group_id_1 { get; set; }
        public Nullable<long> markmo_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campaign_articul> campaign_articul { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campaign_groups> campaign_groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campaign_participant> campaign_participant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campaign_sub_groups> campaign_sub_groups { get; set; }
        public virtual campaign_types campaign_types { get; set; }
    }
}
