//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtData
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaign_participant
    {
        public long id { get; set; }
        public Nullable<long> campaign_id { get; set; }
        public Nullable<long> card_id { get; set; }
        public Nullable<long> crm_customer_id { get; set; }
        public System.DateTime created { get; set; }
        public string delivery_channel { get; set; }
        public Nullable<bool> control_group { get; set; }
        public Nullable<long> market_id { get; set; }
        public string free { get; set; }
    
        public virtual campaigns_mk campaigns_mk { get; set; }
    }
}
