//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtData
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaigns_terms
    {
        public long campaigns_terms_id { get; set; }
        public Nullable<long> campaign_id { get; set; }
        public System.DateTime created { get; set; }
        public string short_comment { get; set; }
        public string description { get; set; }
        public Nullable<int> Rn { get; set; }
    }
}
