//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtData
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaign_articul
    {
        public int id { get; set; }
        public Nullable<long> campaign_id { get; set; }
        public string articul { get; set; }
        public Nullable<int> market_id { get; set; }
        public string name { get; set; }
        public string brand { get; set; }
        public Nullable<decimal> buy_price { get; set; }
        public Nullable<decimal> price_shelf_nds { get; set; }
        public Nullable<decimal> margin_current { get; set; }
        public string name_tc { get; set; }
        public Nullable<int> rest { get; set; }
        public string postv { get; set; }
        public string allowed_discount { get; set; }
        public Nullable<decimal> price_nds_after { get; set; }
        public Nullable<int> points { get; set; }
        public Nullable<decimal> margin_action { get; set; }
    
        public virtual campaigns_mk campaigns_mk { get; set; }
    }
}
