//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtData
{
    using System;
    using System.Collections.Generic;
    
    public partial class dict_markets
    {
        public int id { get; set; }
        public string short_name { get; set; }
        public string name { get; set; }
        public string market_name { get; set; }
        public Nullable<bool> is_start { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
    }
}
