//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtData
{
    using System;
    using System.Collections.Generic;
    
    public partial class markmos1
    {
        public long markmo_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> market_id { get; set; }
        public string markets { get; set; }
        public long markmo_type_id { get; set; }
        public string description { get; set; }
        public decimal value { get; set; }
        public string msg_check { get; set; }
        public string msg_gift { get; set; }
        public Nullable<decimal> value_max { get; set; }
        public string msg_serv { get; set; }
        public Nullable<decimal> min_margin { get; set; }
        public bool check_min_margin { get; set; }
        public Nullable<bool> by_request { get; set; }
        public string web_title { get; set; }
        public string web_short_description { get; set; }
        public Nullable<int> distinct_cnt { get; set; }
        public Nullable<decimal> max_amount { get; set; }
    }
}
