//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoyaltyDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class markmo_types
    {
        public int markmo_type_id { get; set; }
        public string title { get; set; }
        public Nullable<int> is_card_binding_obligatory { get; set; }
    }
}
