//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtData
{
    using System;
    
    public partial class tf_campaign_customers
    {
        public Nullable<long> number { get; set; }
        public string name1 { get; set; }
        public string name2 { get; set; }
        public string name3 { get; set; }
        public string gender { get; set; }
        public string barcode { get; set; }
        public string mobile_phone { get; set; }
        public string control_group { get; set; }
        public string delivery_channel { get; set; }
        public string market_name { get; set; }
    }
}
