//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtData
{
    using System;
    
    public partial class UPLOAD_CONTROL
    {
        public string city { get; set; }
        public Nullable<decimal> customers_qty { get; set; }
        public Nullable<decimal> diff_customers_qty { get; set; }
        public int is_alert_customers_qty { get; set; }
        public Nullable<decimal> card_issued_qty { get; set; }
        public Nullable<decimal> diff_card_issued_qty { get; set; }
        public int is_alert_card_issued_qty { get; set; }
        public Nullable<decimal> knk_qty { get; set; }
        public Nullable<decimal> diff_knk_qty { get; set; }
        public int is_alert_knk_qty { get; set; }
        public Nullable<decimal> qty_doc { get; set; }
        public Nullable<decimal> diff_qty_doc { get; set; }
        public int is_alert_qty_doc { get; set; }
        public Nullable<decimal> rrz_qty { get; set; }
        public Nullable<decimal> diff_rrz_qty { get; set; }
        public int is_alert_rrz_qty { get; set; }
        public Nullable<decimal> qty_sell_record_qty { get; set; }
        public Nullable<decimal> diff_qty_sell_record_qty { get; set; }
        public int is_alert_qty_sell_record_qty { get; set; }
    }
}
