//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_campaigns_mk_run
    {
        public long id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public bool is_run { get; set; }
        public Nullable<long> type_id { get; set; }
        public Nullable<decimal> margin_markets { get; set; }
        public Nullable<decimal> margin_lavel_0 { get; set; }
        public Nullable<decimal> margin_lavel_1 { get; set; }
        public Nullable<decimal> margin_lavel_2 { get; set; }
        public Nullable<decimal> margin_lavel_3 { get; set; }
        public Nullable<long> group_id_0 { get; set; }
        public Nullable<long> group_id_1 { get; set; }
        public Nullable<long> markmo_id { get; set; }
    }
}
