//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_fgroups
    {
        public long fgroup_id { get; set; }
        public string name { get; set; }
        public string comments { get; set; }
        public long parent_id { get; set; }
        public int level_id { get; set; }
        public Nullable<long> author_id { get; set; }
        public long department_id { get; set; }
        public long deleted { get; set; }
        public long is_unload { get; set; }
        public long pperson_id { get; set; }
        public string name_ru { get; set; }
        public bool clear_forbidden { get; set; }
        public byte mt_months { get; set; }
        public bool is_virtual { get; set; }
        public long vdepartment_id { get; set; }
    }
}
